/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;

/**
 *
 * @author Frandy
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public JButton getberanda_btn() {
        return beranda_btn;
    }
        public JButton getsppk_btn() {
        return sppk_btn;
    }
            public JButton gethasil_btn() {
        return hasil_btn;
    }
         public JButton getkeluar_btn() {
        return keluar_btn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        beranda_btn = new javax.swing.JButton();
        sppk_btn = new javax.swing.JButton();
        hasil_btn = new javax.swing.JButton();
        keluar_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 348));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 500, 340));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\frandy\\Kuliah\\akademik\\Semester 6\\SPPK\\sppk\\2.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 10, 640, 60));

        beranda_btn.setIcon(new javax.swing.ImageIcon("D:\\frandy\\Kuliah\\akademik\\Semester 6\\SPPK\\sppk\\beranda1.png")); // NOI18N
        getContentPane().add(beranda_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 140, -1));

        sppk_btn.setIcon(new javax.swing.ImageIcon("D:\\frandy\\Kuliah\\akademik\\Semester 6\\SPPK\\sppk\\sppk.png")); // NOI18N
        sppk_btn.setPreferredSize(new java.awt.Dimension(133, 39));
        getContentPane().add(sppk_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, -1));

        hasil_btn.setIcon(new javax.swing.ImageIcon("D:\\frandy\\Kuliah\\akademik\\Semester 6\\SPPK\\sppk\\hasil.png")); // NOI18N
        hasil_btn.setPreferredSize(new java.awt.Dimension(133, 39));
        getContentPane().add(hasil_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, -1));

        keluar_btn.setIcon(new javax.swing.ImageIcon("D:\\frandy\\Kuliah\\akademik\\Semester 6\\SPPK\\sppk\\keluar.png")); // NOI18N
        keluar_btn.setPreferredSize(new java.awt.Dimension(133, 39));
        getContentPane().add(keluar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\frandy\\Kuliah\\akademik\\Semester 6\\SPPK\\sppk\\1e246c5da84d9c317543e22917f9b8db.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 425));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beranda_btn;
    private javax.swing.JButton hasil_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton keluar_btn;
    private javax.swing.JButton sppk_btn;
    // End of variables declaration//GEN-END:variables
}
